/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '15. 2. 21 오후 2:45' with Gradle 2.0
 *
 * @author Administrator, @date 15. 2. 21 오후 2:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
